FROM emscripten/emsdk:3.1.74

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ninja-build \
        zip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

ENTRYPOINT ["bash", "/src/scripts/build-web.sh"]
